export const ArchiveData = [
    {
        _teamId: "120393",
        year: "2024",
        title: "A Comprehensive Guide to Modern Technology",
        school: "Harvard University",
        projectPics: ["/images/archive/1.jpg", "/images/archive/2.jpg", "/images/archive/4.jpg", "/images/archive/3.jpg"],
        teamName: "Team 1",
        students: ["Tareq Rahman", "Jane Doe", "John Smith"],
        countries: ["USA", "Canada", "UK"],

        videoId: "T7u2KmgDvrk",
        projectPDF: "/files/brief01.pdf",
        desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!", "is eget, consectetur adipiscing elit. Nullam eget fel", "is eget, consectetur adipiscing elit. Nullam eget fel", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!"],
    },
    {
        _teamId: "120394",
        year: "2023",
        title: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        school: "Yale University",
        projectPics: ["/images/archive/1.jpg", "/images/archive/4.jpg", "/images/archive/3.jpg"],
        teamName: "Team 2",
        students: ["Tareq Rahman", "Jane Doe", "John Smith"],
        countires: ["USA", "Canada", "UK"],
        videoId: "T7u2KmgDvrk",
        projectPDF: "/pdf/Project.pdf",
        desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!", "is eget, consectetur adipiscing elit. Nullam eget fel", "is eget, consectetur adipiscing elit. Nullam eget fel", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!"],
    },
    {
        _teamId: "120395",
        year: "2022",
        title: "Dolor sit amet",
        school: "Stanford University",
        projectPics: ["/images/archive/2.jpg", "/images/archive/3.jpg", "/images/archive/4.jpg"],
        teamName: "Team 3",
        students: ["Tareq Rahman", "Jane Doe", "John Smith"],
        countires: ["USA", "Canada", "UK"],

        videoId: "T7u2KmgDvrk",
        projectPDF: "/pdf/Project.pdf",
        desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!", "is eget, consectetur adipiscing elit. Nullam eget fel", "is eget, consectetur adipiscing elit. Nullam eget fel", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!"],
    },
    {
        _teamId: "120396",
        year: "2024",
        title: "A Comprehensive Guide to Modern Technology",
        school: "Harvard University",
        projectPics: ["/images/archive/3.jpg", "/images/archive/4.jpg"],
        teamName: "Team 1",
        students: ["Tareq Rahman", "Jane Doe", "John Smith"],
        countires: ["USA", "Canada", "UK"],

        videoId: "T7u2KmgDvrk",
        projectPDF: "/pdf/Project.pdf",
        desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!", "is eget, consectetur adipiscing elit. Nullam eget fel", "is eget, consectetur adipiscing elit. Nullam eget fel", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!"],
    },
    {
        _teamId: "120397",
        year: "2023",
        title: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        school: "Yale University",
        projectPics: ["/images/archive/3.jpg"],
        teamName: "Team 2",
        students: ["Tareq Rahman", "Jane Doe", "John Smith"],
        countires: ["USA", "Canada", "UK"],

        videoId: "T7u2KmgDvrk",
        projectPDF: "/pdf/Project.pdf",
        desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!", "is eget, consectetur adipiscing elit. Nullam eget fel", "is eget, consectetur adipiscing elit. Nullam eget fel", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!"],
    },
    {
        _teamId: "120398",
        year: "2022",
        title: "Dolor sit amet",
        school: "Stanford University",
        projectPics: ["/images/archive/2.jpg", "/images/archive/3.jpg", "/images/archive/4.jpg"],
        teamName: "Team 3",
        students: ["Tareq Rahman", "Jane Doe", "John Smith"],
        countires: ["USA", "Canada", "UK"],

        videoId: "T7u2KmgDvrk",
        projectPDF: "/pdf/Project.pdf",
        desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!", "is eget, consectetur adipiscing elit. Nullam eget fel", "is eget, consectetur adipiscing elit. Nullam eget fel", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!"],
    },
    {
        _teamId: "120399",
        year: "2024",
        title: "A Comprehensive Guide to Modern Technology",
        school: "Harvard University",
        projectPics: ["/images/archive/1.jpg", "/images/archive/2.jpg", "/images/archive/3.jpg", "/images/archive/4.jpg"],
        teamName: "Team 1",
        students: ["Tareq Rahman", "Jane Doe", "John Smith"],
        countires: ["USA", "Canada", "UK"],

        videoId: "T7u2KmgDvrk",
        projectPDF: "/pdf/Project.pdf",
        desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laud"],
    }
]