export const Publication_Data = [
  {
    
    studentName: "Alan Wood",
    studentTitle: "Architect",
    studentImg: "/images/jury/2.jpg",
    year: "2024",
    client: "Ambient Zone",
    location: "Banani, Dhaka",
    country: "Bangladesh",
    title: "A Comprehensive Guide to Modern Technology",
    school: "Harvard University",
    projectPics: ["/images/Publication/1.jpg", "/images/archive/2.jpg", "/images/archive/4.jpg", "/images/archive/3.jpg"],
    videoId: "T7u2KmgDvrk",
    projectPDF: "/files/brief01.pdf",
    desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!", "is eget, consectetur adipiscing elit. Nullam eget fel", "is eget, consectetur adipiscing elit. Nullam eget fel", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!"],
  },
  {
    
    studentName: "Marlin Brando",
    studentTitle: "Architect",
    studentImg: "/images/jury/1.jpg",
    year: "2024",
    client: "Ambient Zone",
    location: "Banani, Dhaka",
    country: "Bangladesh",
    title: "A Comprehensive Guide to Modern Technology",
    school: "Harvard University",
    projectPics: ["/images/Publication/2.jpg", "/images/archive/2.jpg", "/images/archive/4.jpg", "/images/archive/3.jpg"],
    videoId: "T7u2KmgDvrk",
    projectPDF: "/files/brief01.pdf",
    desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!", "is eget, consectetur adipiscing elit. Nullam eget fel", "is eget, consectetur adipiscing elit. Nullam eget fel", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!"],
  },
  {
    
    studentName: "Joshua",
    studentTitle: "Architect",
    studentImg: "/images/jury/2.jpg",
    year: "2024",
    client: "Ambient Zone",
    location: "Banani, Dhaka",
    country: "Bangladesh",
    title: "A Comprehensive Guide to Modern Technology",
    school: "Harvard University",
    projectPics: ["/images/Publication/3.jpg", "/images/archive/2.jpg", "/images/archive/4.jpg", "/images/archive/3.jpg"],
    videoId: "T7u2KmgDvrk",
    projectPDF: "/files/brief01.pdf",
    desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!", "is eget, consectetur adipiscing elit. Nullam eget fel", "is eget, consectetur adipiscing elit. Nullam eget fel", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!"],
  },
  {
    
    studentName: "Rumi",
    studentTitle: "Architect",
    studentImg: "/images/jury/1.jpg",
    year: "2024",
    client: "Ambient Zone",
    location: "Banani, Dhaka",
    country: "Bangladesh",
    title: "A Comprehensive Guide to Modern Technology",
    school: "Harvard University",
    projectPics: ["/images/Publication/4.jpg", "/images/archive/2.jpg", "/images/archive/4.jpg", "/images/archive/3.jpg"],
    videoId: "T7u2KmgDvrk",
    projectPDF: "/files/brief01.pdf",
    desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!", "is eget, consectetur adipiscing elit. Nullam eget fel", "is eget, consectetur adipiscing elit. Nullam eget fel", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!"],
  },
  {
    
    studentName: "Tareq Rahman",
    studentTitle: "Architect",
    studentImg: "/images/jury/4.jpg",
    year: "2024",
    client: "Ambient Zone",
    location: "Banani, Dhaka",
    country: "Bangladesh",
    title: "A Comprehensive Guide to Modern Technology",
    school: "Harvard University",
    projectPics: ["/images/Publication/6.jpg", "/images/archive/2.jpg", "/images/archive/4.jpg", "/images/archive/3.jpg"],
    videoId: "T7u2KmgDvrk",
    projectPDF: "/files/brief01.pdf",
    desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!", "is eget, consectetur adipiscing elit. Nullam eget fel", "is eget, consectetur adipiscing elit. Nullam eget fel", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!"],
  },
  {
    
    studentName: "Harry Potter",
    studentTitle: "Architect",
    studentImg: "/images/jury/4.jpg",
    year: "2024",
    client: "Ambient Zone",
    location: "Banani, Dhaka",
    country: "Bangladesh",
    title: "A Comprehensive Guide to Modern Technology",
    school: "Harvard University",
    projectPics: ["/images/Publication/5.jpg", "/images/archive/2.jpg", "/images/archive/4.jpg", "/images/archive/3.jpg"],
    videoId: "T7u2KmgDvrk",
    projectPDF: "/files/brief01.pdf",
    desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!", "is eget, consectetur adipiscing elit. Nullam eget fel", "is eget, consectetur adipiscing elit. Nullam eget fel", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!"],
  },
  {
    
    studentName: "Abrar Hossain",
    studentTitle: "Architect",
    studentImg: "/images/jury/2.jpg",
    year: "2024",
    client: "Ambient Zone",
    location: "Banani, Dhaka",
    country: "Bangladesh",
    title: "A Comprehensive Guide to Modern Technology",
    school: "Harvard University",
    projectPics: ["/images/Publication/7.jpg", "/images/archive/2.jpg", "/images/archive/4.jpg", "/images/archive/3.jpg"],
    videoId: "T7u2KmgDvrk",
    projectPDF: "/files/brief01.pdf",
    desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!", "is eget, consectetur adipiscing elit. Nullam eget fel", "is eget, consectetur adipiscing elit. Nullam eget fel", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!"],
  },
  {
    
    studentName: "Samantha Smith",
    studentTitle: "Architect",
    studentImg: "/images/jury/3.jpg",
    year: "2024",
    client: "Ambient Zone",
    location: "Banani, Dhaka",
    country: "Bangladesh",
    title: "A Comprehensive Guide to Modern Technology",
    school: "Harvard University",
    projectPics: ["/images/Publication/8.jpg", "/images/archive/2.jpg", "/images/archive/4.jpg", "/images/archive/3.jpg"],
    videoId: "T7u2KmgDvrk",
    projectPDF: "/files/brief01.pdf",
    desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!", "is eget, consectetur adipiscing elit. Nullam eget fel", "is eget, consectetur adipiscing elit. Nullam eget fel", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!"],
  },
  {
    
    studentName: "Amily Doe",
    studentTitle: "Architect",
    studentImg: "/images/jury/3.jpg",
    year: "2024",
    client: "Ambient Zone",
    location: "Banani, Dhaka",
    country: "Bangladesh",
    title: "A Comprehensive Guide to Modern Technology",
    school: "Harvard University",
    projectPics: ["/images/Publication/9.jpg", "/images/archive/2.jpg", "/images/archive/4.jpg", "/images/archive/3.jpg"],
    videoId: "T7u2KmgDvrk",
    projectPDF: "/files/brief01.pdf",
    desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!", "is eget, consectetur adipiscing elit. Nullam eget fel", "is eget, consectetur adipiscing elit. Nullam eget fel", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui aut deleniti doloribus, distinctio quas expedita soluta, porro laudantium saepe vitae excepturi quibusdam harum laborum quos veniam officia nihil dicta ad delectus repudiandae. Officia vitae nesciunt id eos omnis veritatis nostrum!"],
  },
];
